
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: versequest-backend
    environment:
      - PPLX_API_KEY=${PPLX_API_KEY}
    ports:
      - "8000:8000"
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: versequest-web
    environment:
      - VITE_API_URL=http://localhost:8000/api/explain
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped
